INSERT INTO DIM_CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, EMAIL) VALUES (1, 'Acme Corp', 'contact@acme.com');
INSERT INTO DIM_CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, EMAIL) VALUES (2, 'Globex', 'sales@globex.com');

INSERT INTO DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, CATEGORY) VALUES (101, 'Widget', 'Hardware');
INSERT INTO DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, CATEGORY) VALUES (102, 'Gadget', 'Electronics');

INSERT INTO FACT_ORDER (ORDER_ID, CUSTOMER_ID, ORDER_DATE, STATUS) VALUES (1001, 1, DATE '2024-01-10', 'NEW');
INSERT INTO FACT_ORDER (ORDER_ID, CUSTOMER_ID, ORDER_DATE, STATUS) VALUES (1002, 2, DATE '2024-01-12', 'SHIPPED');

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (5001, 1001, 101, 2, 19.99);
INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (5002, 1001, 102, 1, 49.99);
