CREATE TABLE DIM_CUSTOMER (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(100),
    EMAIL VARCHAR2(150)
);

CREATE TABLE DIM_PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(120),
    CATEGORY VARCHAR2(80)
);

CREATE TABLE FACT_ORDER (
    ORDER_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    ORDER_DATE DATE,
    STATUS VARCHAR2(40)
);

CREATE TABLE FACT_ORDER_LINE (
    ORDER_LINE_ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2)
);
